#!/usr/bin/env bash

# Perennial Task Installation Script
# This script must be run with sudo privileges.

# --- Configuration ---
APP_NAME="perennial-task"
EXECUTABLE_NAME="prn"
INSTALL_DIR="/usr/local/lib/$APP_NAME"
BIN_DIR="/usr/local/bin"
SCHEMA_NAME="task.xsd"
COMPLETIONS_SCRIPT="prn-completions.bash"

# --- Pre-flight Checks ---
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root or with sudo." 
    exit 1
fi

echo "Starting Perennial Task installation..."

# --- Installation Steps ---
echo "Creating application directory at $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR" || { echo "Error: Could not create directory $INSTALL_DIR. Aborting."; exit 1; }

echo "Copying application files..."
(
  shopt -s nullglob
  cp ./*.php "$INSTALL_DIR/"
  cp ./*.xsd "$INSTALL_DIR/"
  cp ./"$EXECUTABLE_NAME" "$INSTALL_DIR/"
  cp ./"$COMPLETIONS_SCRIPT" "$INSTALL_DIR/"
) || { echo "Error: Failed to copy application files. Aborting."; exit 1; }

echo "Setting file permissions..."
chmod +x "$INSTALL_DIR/$EXECUTABLE_NAME"

echo "Creating symbolic link at $BIN_DIR/$EXECUTABLE_NAME..."
ln -sf "$INSTALL_DIR/$EXECUTABLE_NAME" "$BIN_DIR/$EXECUTABLE_NAME" || { echo "Error: Could not create symbolic link. Aborting."; exit 1; }

# --- Install Bash Completions ---
echo "Installing bash completions..."
COMPLETIONS_DIR=""
if [ -d "/usr/share/bash-completion/completions" ]; then
    COMPLETIONS_DIR="/usr/share/bash-completion/completions"
elif [ -d "/etc/bash_completion.d" ]; then
    COMPLETIONS_DIR="/etc/bash_completion.d"
fi

if [ -n "$COMPLETIONS_DIR" ]; then
    ln -sf "$INSTALL_DIR/$COMPLETIONS_SCRIPT" "$COMPLETIONS_DIR/$EXECUTABLE_NAME"
    if [ $? -eq 0 ]; then
        echo "Bash completions installed. Please restart your shell or run 'source $COMPLETIONS_DIR/$EXECUTABLE_NAME' to enable them."
    else
        echo "Warning: Could not install bash completions."
    fi
else
    echo "Warning: Could not find a bash completion directory. Completions not installed."
fi

# --- User-specific Setup ---
USER_HOME=""
if [ -n "$SUDO_USER" ]; then
    USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
    echo "Warning: Could not determine the original user. User-specific configuration will be skipped."
    # Exit gracefully, as the system-wide part of the installation is complete.
    exit 0
fi

# Determine the base config directory according to XDG Base Directory Specification.
# If XDG_CONFIG_HOME is set (e.g., via `sudo -E`), we use it. Otherwise, we default to $HOME/.config.
if [[ -n "$XDG_CONFIG_HOME" && -d "$XDG_CONFIG_HOME" ]]; then
    CONFIG_BASE="$XDG_CONFIG_HOME"
else
    CONFIG_BASE="$USER_HOME/.config"
fi

USER_CONFIG_DIR="$CONFIG_BASE/$APP_NAME"
USER_TASKS_DIR="$USER_CONFIG_DIR/tasks"

echo "Creating user configuration directory at $USER_CONFIG_DIR..."
mkdir -p "$USER_TASKS_DIR" || { echo "Error: Could not create directory $USER_TASKS_DIR. Aborting."; exit 1; }

CONFIG_FILE="$USER_CONFIG_DIR/config.ini"

# --- Create config.ini (if it doesn't exist) ---
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Creating new configuration file at $CONFIG_FILE..."
    cat << EOF > "$CONFIG_FILE"
; Perennial Task Configuration File
; This file is automatically generated by the installer.
; You can edit these paths and settings.

tasks_dir = "$USER_TASKS_DIR"
completions_log = "$USER_CONFIG_DIR/completions.log"
xsd_path = "$INSTALL_DIR/$SCHEMA_NAME"
tasks_per_page = 10
EOF
else
    echo "Configuration file already exists at $CONFIG_FILE. Skipping creation."
fi

# Set correct ownership for the application's user config directory.
echo "Setting ownership for $USER_CONFIG_DIR..."
chown -R "$SUDO_USER:$SUDO_USER" "$USER_CONFIG_DIR" || echo "Warning: Could not set ownership for $USER_CONFIG_DIR."

# --- Finalization ---
echo ""
echo "-------------------------------------------"
echo " Perennial Task installation complete!"
echo "-------------------------------------------"
echo "You can now use the 'prn' command from anywhere in your terminal."
echo "Your configuration is located at: $CONFIG_FILE"
echo "Run 'prn help' to get started."
echo ""

exit 0

